### ISSUE TITLE
Is it not possible to create just a box?

### ISSUE THREAD

**Issue by midosvt** [nexquery/samp-textdraw-editor#13]
Hello, I recently began using this textdraw editor about a week ago. I've had an issue with Nick's version, as it doesn't support open.mp. As a result, I have been modifying and playing with the code to make it work. However, I have now realized that there doesn't seem to be an option to create a box. It's possible that I might have overlooked it, but I would greatly appreciate a response to clarify this matter.

**Comment by midosvt** [comment]
Thanks. And great work btw, keep it up

**Comment by nexquery** [comment]
Thanks, I'm thinking of making a tool like texture studio soon.
