### ISSUE TITLE
Which menu can't you see? (icons)

### ISSUE THREAD

**Issue by nikxso** [nexquery/samp-textdraw-editor#7]
Which menu can't you see?

_Originally posted by @nexquery in https://github.com/nexquery/samp-textdraw-editor/issues/3#issuecomment-1170403497_
           
>I have a problem that I don't know why the menu appears invisible and I have tried >everything and nothing has worked for me, any help?

True, same thing happning with me as i tried many time. when we click on the empty spaces function call and the dialogs occurs but we aren't able to see the icon.
see https://nike.has.rocks/tde.avi

**Comment by nexquery** [comment]
I can't watch the video, can you upload it elsewhere?

**Comment by nexquery** [comment]
I think there is a problem with the model download

**Comment by NIKEDev** [comment]
> I think there is a problem with the model download

Ive also tried to put NEXTDE.txd file in gtaroot/models/txd with using the 037 version server but still no changes

**Comment by NIKEDev** [comment]
> I can't watch the video, can you upload it elsewhere?

https://cdn.discordapp.com/attachments/749321998659879003/1073105121883455551/tde.avi

**Comment by nexquery** [comment]
> 

this is very interesting, it should work properly under normal conditions.

**Comment by nexquery** [comment]
> > I think there is a problem with the model download
> 
> Ive also tried to put NEXTDE.txd file in gtaroot/models/txd with using the 037 version server but still no changes

this is very interesting, it should work properly under normal conditions.

**Comment by nexquery** [comment]
Can you show how this problem arose from the very beginning?

**Comment by NIKEDev** [comment]
Well, I've download the last version of nextde and triad to setup for both 037 & dl version, in both I found the icon actually doesn't shows on screen but the backwards logic works properly. I'm running this on my win7 system. I think an issue with system or the .txd file

**Comment by nexquery** [comment]
Can you add me on discord, I would like to solve this problem quickly.  Nexor#4730

**Comment by nexquery** [comment]
I think this question is related to DXT.

**Comment by nexquery** [comment]
The files you uploaded have been merged with the repository, I'm closing the issue assuming this issue has been resolved.
